enum ItemType {
    TXTAREA = 'textarea',
    TXT = 'text',
    COLOR = 'color',
    FONT = 'font'
}

interface inputs {
    name: String,
    keyName: String,
    val: String,
    type: ItemType,
    isUrl: Boolean,
    title: String,
    shouldShow: Boolean,
}

export const config: Array<inputs> = [
    {
        name: 'Redirect When User Clicks Logo',
        keyName: 'logoHref',
        val: '',
        type: ItemType.TXT,
        isUrl: true,
        title: 'Where to redirect the user if they click the logo.',
        shouldShow: true,
        
    },
    {
        name: 'Your Logo URL.',
        keyName: 'logoSrc',
        val: '/favicon.ico',
        type: ItemType.TXT,
        isUrl: true,
        title: 'A valid URL for your logo.',
        shouldShow: true,
    },
    {
        name: 'Button Links To',
        keyName: 'ctaButtonHref',
        val: '',
        isUrl: true,
        type: ItemType.TXT,
        title: 'Where the user is redirected to when they click the button',
        shouldShow: true,
    },
    {
        name: 'Button Text',
        keyName: 'ctaButtonText',
        val: 'Click me!',
        type: ItemType.TXT,
        isUrl: false,
        title: 'The text displayed on the emails button.',
        shouldShow: true,
    },
    {
        name: 'Unsubscribe Link',
        keyName: 'unsubHref',
        val: '',
        isUrl: true,
        type: ItemType.TXT,
        title: 'Where to redirect the user if they click the unsubscribe link.',
        shouldShow: true,
    },
    {
        name: 'Main Heading Text',
        keyName: 'heroHeadingText',
        val: 'Enter A Heading...',
        type: ItemType.TXTAREA,
        isUrl: false,
        title: 'The main heading for the email',
        shouldShow: true,
    },
    {
        name: 'Email Body Text',
        keyName: 'emailBodyText',
        val: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        type: ItemType.TXTAREA,
        isUrl: false,
        title: 'The main text displayed in the email body.',
        shouldShow: true,
    },
    {
        name: 'Preheader',
        keyName: 'preheader',
        val: 'Preheader is shown as a preview in some email clients, seen by users before opening a message.',
        type: ItemType.TXTAREA,
        isUrl: false,
        title: 'Preheader is shown as a preview in some email clients, seen by users before opening a message.',
        shouldShow: true,
    },
    {
        name: 'Final Text in Email',
        keyName: 'finalContentText',
        val: 'Some more words to display after the button.',
        type: ItemType.TXTAREA,
        isUrl: false,
        title: 'Final text block in the email body.',
        shouldShow: true,
    },
    {
        name: 'Final Body Text',
        keyName: 'afterBodyText',
        val: 'I could be something small, most emails use something like; you are recieving this email because....',
        type: ItemType.TXTAREA,
        isUrl: false,
        title: 'Small text after the email body.',
        shouldShow: true,
    },
]